
# This is the project ID of the Supabase project
project_id = "yvtdpfampfndlnjqoocm"

[api]
enabled = true

[db]
enabled = true

[analytics]
enabled = false

[realtime]
enabled = false

[edge_functions]
enabled = true

[functions.mollie-webhook]
verify_jwt = false

[functions.express-webhook]
verify_jwt = false

[functions.mollie-check-payment]
verify_jwt = false

[functions.mollie-create-payment]
verify_jwt = true

[functions.mollie-setup-subscription]
verify_jwt = true
