
/**
 * Utility functions for handling prompt examples and text transformations
 */

// Complete list of example prompts
export const examplePrompts = [
  "French Tips avec un dégradé de bleu",
  "Ombre Fade avec des accents dorés",
  "Marble Effect inspiré par un coucher de soleil",
  "Glitter Accent avec des motifs fleuris",
  "Chrome Finish avec des détails argentés",
  "Matte and Glossy Combo avec des motifs minimalistes",
  "Minimalist Lines en rose gold",
  "Negative Space Art avec des paillettes holographiques",
  "Floral Patterns avec une touche métallique",
  "Animal Print avec des détails argentés",
  "Stars and Moon avec un effet galaxie",
  "Tie-Dye Effect avec des tons pastel",
  "Gold Foil Accents sur fond noir mat",
  "Marble French Tips avec une touche d'or",
  "Holographic Nails avec des reflets multicolores",
  "Abstract Art inspiré par Kandinsky",
  "Dripping Paint Effect avec des couleurs contrastées",
  "Checkerboard Print en noir et blanc",
  "Neon Glow avec des effets phosphorescents",
  "Galaxy Design avec des paillettes étoilées",
  "Butterfly Wings avec des détails délicats",
  "Polka Dots en couleurs vives",
  "3D Embellishments avec des pierres précieuses",
  "Matte Black with Gold Accents pour un look élégant",
  "Mix & Match Designs pour un style unique",
  "Geometric Lines avec un dégradé de couleurs",
  "Color Block avec des frontières nettes",
  "Foil Stripes avec un effet métallique",
  "Crystal Embellishments pour une occasion spéciale",
  "Pearl Accents avec une finition nacre",
  "Watercolor Effect avec des couleurs qui se fondent",
  "Splatter Paint comme une toile d'artiste",
  "Flame Design avec des tons orangés et rouges",
  "Wave Patterns inspiré par l'océan",
  "Cartoon Art avec des personnages amusants",
  "Pastel Gradient du plus clair au plus foncé",
  "Candy Swirls avec des couleurs sucrées",
  "Smiley Faces pour un look joyeux",
  "Cloud Nails avec un effet aérien",
  "Textured Velvet avec un toucher doux",
  "Quartz Effect avec des reflets cristallins",
  "Metallic Drips comme du métal en fusion",
  "Neon French Tips pour un look moderne",
  "Tortoiseshell Print avec des tons ambrés",
  "Jelly Nails avec un effet transparent",
  "Sharp Edge Tips pour un look audacieux",
  "Aurora Borealis inspiré par les aurores boréales",
  "Floral Stamping avec des motifs détaillés",
  "Psychedelic Swirls aux couleurs vibrantes",
  "Minimalist Dots pour un style épuré",
  "Starburst Design avec un effet rayonnant",
  "Gemstone-Inspired aux couleurs de pierres précieuses",
  "Metallic Half-Moon avec un contraste élégant",
  "Holo Glitter Tips scintillants et changeants",
  "Abstract Splashes comme un tableau moderne",
  "Psychedelic Checkerboard multicolore",
  "Foil Marble avec des veines métalliques",
  "Edgy Negative Space pour un style contemporain",
  "Reverse French Manicure inversant les codes classiques",
  "Bold Outlined Nails avec des contours marqués",
  "Confetti Nails pour célébrer en style",
  "Pop Art Designs inspiré par Warhol",
  "Transparent Layers avec des superpositions",
  "Swirling Stripes en spirales colorées",
  "Lace Pattern délicat et élégant",
  "Snowflake Design pour un hiver féerique",
  "Mermaid Scales aux reflets irisés",
  "Pumpkin Spice Theme pour l'automne",
  "Spiderweb Accent pour Halloween",
  "Electric Lightning Bolts énergiques",
  "Holiday Ornament Nails festifs",
  "Cosmic Dust avec des paillettes stellaires",
  "Tropical Palm Leaves pour un style estival",
  "Multi-Texture Nails combinant différentes finitions",
  "Futuristic Cyberpunk Style audacieux",
  "Christmas Ornaments pour les fêtes",
  "Candy Cane Stripes rouge et blanc",
  "Reindeer Silhouettes pour Noël",
  "Santa Hat Tips festifs",
  "Christmas Tree Accents décorés",
  "Gingerbread Man Nails gourmands",
  "Festive Plaid aux motifs écossais",
  "Holly and Berries traditionnels",
  "Frosty Ice Effect glacé",
  "Easter Egg Patterns colorés",
  "Pastel Bunny Accents pour Pâques",
  "Floral Spring Blooms printaniers",
  "Speckled Egg Design moucheté",
  "Cute Chick Art jaune et adorable",
  "Valentine's Heart Tips romantiques",
  "Love Letter Accents avec des messages",
  "Red Roses Design passionné",
  "Cupid Arrow Details pour la Saint-Valentin",
  "Pink Ombre Love dégradé tendre",
  "Neon Summer Sunset éclatant",
  "Palm Tree Silhouettes tropicales",
  "Ocean Wave Accents bleu azur",
  "Tropical Fruit Prints exotiques",
  "Ice Cream Cone Nails gourmands",
  "Beach Sand Texture ensoleillée",
  "Autumn Leaves Gradient automnal",
  "Pumpkin Spice Swirls chaleureux",
  "Halloween Spiderwebs mystérieux",
  "Black Cat Accents porte-bonheur",
  "Spooky Ghost Nails pour Halloween",
  "Bat Silhouette Tips nocturnes",
  "Glow-in-the-Dark Halloween phosphorescent",
  "Thanksgiving Turkey Feathers festifs",
  "Cozy Sweater Knit Design hivernal",
  "Festive Fireworks éclatants",
  "Champagne Bubbles pétillants",
  "Birthday Confetti joyeux",
  "Galaxy New Year Theme cosmique",
  "Shamrock Green Tips porte-bonheur",
  "Rainbow Pride Stripes colorés",
  "Fourth of July Stars patriotiques",
  "Firework Explosions spectaculaires",
  "Mardi Gras Glitter festif",
  "Carnival Confetti multicolore",
  "Sunflower Fields ensoleillé",
  "Back to School Chalkboard nostalgique",
  "Graduation Cap Accents célébratoires",
  "Music Festival Tie-Dye vibrant"
];

/**
 * Gets a random selection of example prompts
 */
export const getRandomExamples = (count = 8) => {
  const shuffled = [...examplePrompts].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

/**
 * Extracts the main concept from a full example prompt
 */
export const extractMainConcept = (example: string): string => {
  return example.split(" avec ")[0].split(" en ")[0].split(" inspiré")[0];
};
